variables:
- group: terraform-os-prod
- name: $projectname
  value: '$(projectname)'
- name: $environment
  value: '$(environment)'
- name: $saterraform
  value: '$(saterraform)'

trigger:
  branches:
    include:
      - os-prod
  paths:
    include:
      - terraform/*

jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'
    displayName: 'Setup terraform artifact'
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: PowerShell@2
        displayName: 'Setup Variable'
        inputs:
          targetType: 'inline'
          script: |
            $rgterraform = "rg-"+"$(projectname)"+"-"+"$(environment)"

            $acrname = "acrfor"+"$(projectname)"+"$(environment)"

            Write-Host "##vso[task.setvariable variable=rgterraform]$rgterraform"

            Write-Host "##vso[task.setvariable variable=acrname]$acrname"
      - task: AzureCLI@2
        displayName: 'Setup Terraform'
        inputs:
          azureSubscription: 'sc-terraform'
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: >-
            if (az group show --name $(rgterraform)) {
                if (az storage account show --name $(saterraform) --resource-group $(rgterraform)) {
                    exit 0
                }
                else {
                    az storage account create --name $(saterraform) --resource-group $(rgterraform) --location southeastasia --sku Standard_LRS

                    az storage container create --name terraform --account-name $(saterraform)

                    az storage account keys list -g $(rgterraform) -n $(saterraform)
                }
            }
            else {
                az group create --name $(rgterraform) --location southeastasia

                az storage account create --name $(saterraform) --resource-group $(rgterraform) --location southeastasia --sku Standard_LRS

                az storage container create --name terraform --account-name $(saterraform)

                az storage account keys list -g $(rgterraform) -n $(saterraform)
            }
          powerShellErrorActionPreference: stop
      - task: replacetokens@5
        displayName: Setup config for terraform
        inputs:
          rootDirectory: terraform
          targetFiles: '*.tf'
          tokenPattern: rm
      - task: PublishPipelineArtifact@1
        displayName: Publish terraform Artifact
        inputs:
          path: terraform
          artifactName: terraform